import mongoose from "mongoose";

// Defining Schema
const ac2tSchema = new mongoose.Schema({
  BOGIE_TYPE_NO:                                            { type: String,  trim: true },
  SHIFT:                                            { type: String,  trim: true },
  APPLICABLE_WI_NO:                                          { type: String,  trim: true },
  FRAME_NO_MAKE:                           { type: String,  trim: true },
  WHEEL_AXLE_NO:                                          { type: String,  trim: true },
  BRAKE_CYLINDER_NO_MAKE:                                                                       { type: String,  trim: true },
  VSA_PRIMARY_SUSP_NO_MAKE:                                             { type: String,  trim: true },
  VSA_SECONDARY_SUSP_NO_MAKE:                                     { type: String,  trim: true },
  LATERAL_SHOCK_ABSORBER_NO_MAKE:                                       { type: String,  trim: true },
  BOLSTER_NO_MAKE:                                                { type: String,  trim: true },
  Z11_TARE:                                                  { type: String,  trim: true },
  Z11_TARE_REMARK:                                                 { type: String, trim: true },
  Z11_GROSS:                                                 { type: String,  trim: true },
  Z11_GROSS_REMARK:                                     { type: String, trim: true },
  Z31_TARE:                                                  { type: String,  trim: true },
  Z31_TARE_REMARK:                                       { type: String, trim: true },
  Z31_GROSS:                                        { type: String,  trim: true },
  Z31_GROSS_REMARK:                                         { type: String, trim: true },
  Z41_TARE:                                    { type: String,  trim: true },
  Z41_TARE_REMARK:                                            { type: String, trim: true },
  Z41_GROSS:                                { type: String,  trim: true },
  Z41_GROSS_REMARK:                                                  { type: String, trim: true },
  Z21_TARE:                                             { type: String,  trim: true },
  Z21_TARE_REMARK:                                     { type: String, trim: true },
  Z21_GROSS:                                         { type: String,  trim: true },
  Z21_GROSS_REMARK:                                          { type: String, trim: true },
  X_TARE:                                                { type: String,  trim: true },
  X_TARE_REMARK:                                                         { type: String, trim: true },
  X_GROSS:                                     { type: String,  trim: true },
  X_GROSS_REMARK:                                         { type: String, trim: true },
  Z12_PLUS_Z22_BY2_TARE:                                               { type: String,  trim: true },
  Z12_PLUS_Z22_BY2_TARE_REMARK:                                               { type: String, trim: true },
  Z12_PLUS_Z22_BY2_GROSS:                                                             { type: String,  trim: true },
  Z12_PLUS_Z22_BY2_GROSS_REMARK:                                                                  { type: String, trim: true },
  Z32_PLUS_Z42_BY2_TARE:                                          { type: String,  trim: true },
  Z32_PLUS_Z42_BY2_TARE_REMARK:                                   { type: String, trim: true },
  Z32_PLUS_Z42_BY2_GROSS:                                                 { type: String,  trim: true },
  Z32_PLUS_Z42_BY2_GROSS_REMARK:                                          { type: String, trim: true },
  X14_TARE:                                                                       { type: String,  trim: true },
  X14_TARE_REMARK:                                                    { type: String, trim: true },
  X14_GROSS:                                                 { type: String,  trim: true },
  X14_GROSS_REMARK:                                                    { type: String, trim: true },
  X24_TARE:                                                        { type: String,  trim: true },
  X24_TARE_REMARK:                                                           { type: String, trim: true },
  X24_GROSS:                                                                    { type: String,  trim: true },
  X24_GROSS_REMARK:                                                                     { type: String, trim: true },
  Y13_TARE:                                                                  { type: String,  trim: true },
  Y13_TARE_REMARK:                                                               { type: String, trim: true },
  Y13_GROSS:                                                                 { type: String,  trim: true },
  Y13_GROSS_REMARK:                                                            { type: String, trim: true },
  Y33_TARE:                                                    { type: String,  trim: true },
  Y33_TARE_REMARK:                                                    { type: String, trim: true },
  Y33_GROSS:                                           { type: String,  trim: true },
  Y33_GROSS_REMARK:                                     { type: String, trim: true },
  A_SIDE_TARE:                                      { type: String,  trim: true },
  A_SIDE_TARE_REMARK:                                               { type: String, trim: true },
  A_SIDE_GROSS:                               { type: String,  trim: true },
  A_SIDE_GROSS_REMARK:                                { type: String, trim: true },
  B_SIDE_TARE:                                                                  { type: String,  trim: true },
  B_SIDE_TARE_REMARK:                                        { type: String, trim: true },
  B_SIDE_GROSS:                                                                      { type: String,  trim: true },
  B_SIDE_GROSS_REMARK:                                                  { type: String, trim: true },
  TEST_PASSED:                                                        {type:Boolean,required:true},
  Y_TARE:                                                          { type: String,  trim: true },
  Y_GROSS:                                                          { type: String,  trim: true },
  A_TARE:                                                     { type: String,  trim: true },
  B_TARE:                                                    { type: String,  trim: true },
  Z133_PLUS_Z23_BY2_TARE:                                      { type: String,  trim: true },
  Z133_PLUS_Z23_BY2_TARE_REMARK:                                { type: String,  trim: true },
  X_MINUS_1_TARE:                                                 { type: String,  trim: true },
  X_MINUS_1_TARE_REMARK:                                             { type: String,  trim: true },
  Y_MINUS_1_TARE:                                                 { type: String,  trim: true },
  Y_MINUS_1_TARE_REMARK:                                          { type: String,  trim: true },
  X15_TARE:                                                          { type: String,  trim: true },
  X15_TARE_REMARK:                                                   { type: String,  trim: true },
  X25_TARE:                                                          { type: String,  trim: true },
  X25_TARE_REMARK:                                                          { type: String,  trim: true },
  Y14_TARE:                                                            { type: String,  trim: true },
  Y14_TARE_REMARK:                                                      { type: String,  trim: true },
  Y34_TARE:                                                            { type: String,  trim: true },
  Y34_TARE_REMARK:                                                      { type: String,  trim: true },


//M5008
FORM_TYPE:                                                              { type: String,  trim: true },
M5008_Drawing_No:                                                      { type: String,  trim: true },
M5008_Bogie_No:                                                        { type: String,  trim: true },
M5008_for:                                                             { type: String,  trim: true },
M5008_Bogie_Frame_No:                                                  { type: String,  trim: true },
M5008_Date:                                                            { type: String,  trim: true },
M5008_bolster_no:                                                     { type: String,  trim: true },
M5008_cross_section_No:                                                { type: String,  trim: true },
M5008_Axle_Nos_EE:                                                     { type: String,  trim: true },
M5008_Nee:                                                             { type: String,  trim: true },
M5008_Brake_Cylinder_No1:                                              { type: String,  trim: true },
M5008_Brake_Cylinder_No2:                                             { type: String,  trim: true },
M5008_Brake_Cylinder_No3:                                             { type: String,  trim: true },
M5008_Brake_Cylinder_No4:                                             { type: String,  trim: true },
M5008_Brake_Caliper_No1:                                              { type: String,  trim: true },
M5008_Brake_Caliper_No2:                                              { type: String,  trim: true },
M5008_Brake_Caliper_No3:                                              { type: String,  trim: true },
M5008_Brake_Caliper_No4:                                              { type: String,  trim: true },
M5008_Remark1:                                                            { type: String,  trim: true },
M5008_Remark2:                                                            { type: String,  trim: true },
M5008_Remark3:                                                            { type: String,  trim: true },
M5008_Remark4:                                                            { type: String,  trim: true },
M5008_Remark5:                                                            { type: String,  trim: true },
M5008_Remark6:                                                            { type: String,  trim: true },
M5008_Remark7:                                                            { type: String,  trim: true },
M5008_Remark8:                                                            { type: String,  trim: true },
M5008_Remark9:                                                            { type: String,  trim: true },
M5008_Remark10:                                                            { type: String,  trim: true },
M5008_Remark11:                                                            { type: String,  trim: true },
M5008_Remark12:                                                            { type: String,  trim: true },
M5008_Remark13:                                                            { type: String,  trim: true },
M5008_Remark14:                                                            { type: String,  trim: true },
M5008_Remark15:                                                            { type: String,  trim: true },
M5008_Remark16:                                                            { type: String,  trim: true },
M5008_Remark17:                                                            { type: String,  trim: true },
M5008_Remark18:                                                            { type: String,  trim: true },
M5008_Remark19:                                                            { type: String,  trim: true },
M5008_Remark20:                                                            { type: String,  trim: true },
M5008_Remark21:                                                            { type: String,  trim: true },
M5008_Remark22:                                                            { type: String,  trim: true },
M5008_Remark23:                                                            { type: String,  trim: true },M5008_Remark24:                                                            { type: String,  trim: true },
M5008_Remark25:                                                            { type: String,  trim: true },
M5008_Remark26:                                                            { type: String,  trim: true },
M5008_Remark27:                                                            { type: String,  trim: true },
M5008_Remark28:                                                            { type: String,  trim: true },
M5008_Remark29:                                                            { type: String,  trim: true },
M5008_Remark30:                                                            { type: String,  trim: true },
M5008_Remark31:                                                            { type: String,  trim: true },
M5008_Remark32:                                                            { type: String,  trim: true },
M5008_Actual1:                                                            { type: String,  trim: true },
M5008_Actual2:                                                            { type: String,  trim: true },
M5008_Actual3:                                                            { type: String,  trim: true },
M5008_Actual4:                                                            { type: String,  trim: true },
M5008_Actual5:                                                            { type: String,  trim: true },
M5008_Actual6:                                                            { type: String,  trim: true },
M5008_Actual7:                                                            { type: String,  trim: true },
M5008_Actual8:                                                            { type: String,  trim: true },
M5008_Actual9:                                                            { type: String,  trim: true },
M5008_Actual10:                                                            { type: String,  trim: true },
M5008_Actual11:                                                            { type: String,  trim: true },
M5008_Actual12:                                                            { type: String,  trim: true },
M5008_Actual13:                                                            { type: String,  trim: true },
M5008_Actual14:                                                            { type: String,  trim: true },
M5008_Actual15:                                                            { type: String,  trim: true },
M5008_Actual16:                                                            { type: String,  trim: true },
M5008_Actual17:                                                            { type: String,  trim: true },
M5008_Actual18:                                                            { type: String,  trim: true },
M5008_Actual19:                                                            { type: String,  trim: true },
M5008_Actual20:                                                            { type: String,  trim: true },
M5008_Actual21:                                                            { type: String,  trim: true },
M5008_Actual22:                                                            { type: String,  trim: true },
M5008_Actual23:                                                            { type: String,  trim: true },M5008_Actual24:                                                            { type: String,  trim: true },
M5008_Actual25:                                                            { type: String,  trim: true },
M5008_Actual26:                                                            { type: String,  trim: true },
M5008_Actual27:                                                            { type: String,  trim: true },
M5008_Actual28:                                                            { type: String,  trim: true },
M5008_Actual29:                                                            { type: String,  trim: true },
M5008_Actual30:                                                            { type: String,  trim: true },
M5008_Actual31:                                                            { type: String,  trim: true },
M5008_Actual32:                                                            { type: String,  trim: true },


//M5008A
M5008A_Drawing_No:                                                      { type: String,  trim: true },
M5008A_Bogie_No:                                                        { type: String,  trim: true },
M5008A_for:                                                             { type: String,  trim: true },
M5008A_Bogie_Frame_No:                                                  { type: String,  trim: true },
M5008A_Date:                                                            { type: String,  trim: true },
M5008A_shift:                                                           { type: String,  trim: true },
M5008A_bolster_no:                                                     { type: String,  trim: true },
M5008A_cross_section_No:                                                { type: String,  trim: true },
M5008A_Axle_Nos_EE:                                                     { type: String,  trim: true },
M5008A_Nee:                                                             { type: String,  trim: true },
M5008A_Brake_Cylinder_No1:                                              { type: String,  trim: true },
M5008A_Brake_Cylinder_No2:                                             { type: String,  trim: true },
M5008A_Brake_Cylinder_No3:                                             { type: String,  trim: true },
M5008A_Brake_Cylinder_No4:                                             { type: String,  trim: true },
M5008A_Brake_Caliper_No1:                                              { type: String,  trim: true },
M5008A_Brake_Caliper_No2:                                              { type: String,  trim: true },
M5008A_Brake_Caliper_No3:                                              { type: String,  trim: true },
M5008A_Brake_Caliper_No4:                                              { type: String,  trim: true },

//remarks start here
M5008A_Remark2:                                                            { type: String,  trim: true },
M5008A_Remark3:                                                            { type: String,  trim: true },
M5008A_Remark4:                                                            { type: String,  trim: true },
M5008A_Remark5:                                                            { type: String,  trim: true },
M5008A_Remark6:                                                            { type: String,  trim: true },
M5008A_Remark7:                                                            { type: String,  trim: true },
M5008A_Remark8:                                                            { type: String,  trim: true },
M5008A_Remark9:                                                            { type: String,  trim: true },
M5008A_Remark10:                                                            { type: String,  trim: true },
M5008A_Remark11:                                                            { type: String,  trim: true },
M5008A_Remark12:                                                            { type: String,  trim: true },
M5008A_Remark13:                                                            { type: String,  trim: true },
M5008A_Remark14:                                                            { type: String,  trim: true },
M5008A_Remark15:                                                            { type: String,  trim: true },
M5008A_Remark16:                                                            { type: String,  trim: true },
M5008A_Remark17:                                                            { type: String,  trim: true },
M5008A_Remark18:                                                            { type: String,  trim: true },
M5008A_Remark19:                                                            { type: String,  trim: true },
M5008A_Remark20:                                                            { type: String,  trim: true },
M5008A_Remark21:                                                            { type: String,  trim: true },
M5008A_Remark22:                                                            { type: String,  trim: true },
M5008A_Remark23:                                                            { type: String,  trim: true },M5008_Remark24:                                                            { type: String,  trim: true },
M5008A_Remark25:                                                            { type: String,  trim: true },
M5008A_Remark26:                                                            { type: String,  trim: true },
M5008A_Remark27:                                                            { type: String,  trim: true },
M5008A_Remark28:                                                            { type: String,  trim: true },
M5008A_Remark29:                                                            { type: String,  trim: true },
M5008A_Remark30:                                                            { type: String,  trim: true },
M5008A_Remark31:                                                            { type: String,  trim: true },
M5008A_Remark32:                                                            { type: String,  trim: true },
M5008A_Actual1:                                                            { type: String,  trim: true },
M5008A_Actual2:                                                            { type: String,  trim: true },
M5008A_Actual3:                                                            { type: String,  trim: true },
M5008A_Actual4:                                                            { type: String,  trim: true },
M5008A_Actual5:                                                            { type: String,  trim: true },
M5008A_Actual6:                                                            { type: String,  trim: true },
M5008A_Actual7:                                                            { type: String,  trim: true },
M5008A_Actual8:                                                            { type: String,  trim: true },
M5008A_Actual9:                                                            { type: String,  trim: true },
M5008A_Actual10:                                                            { type: String,  trim: true },
M5008A_Actual11:                                                            { type: String,  trim: true },
M5008A_Actual12:                                                            { type: String,  trim: true },
M5008A_Actual13:                                                            { type: String,  trim: true },
M5008A_Actual14:                                                            { type: String,  trim: true },
M5008A_Actual15:                                                            { type: String,  trim: true },
M5008A_Actual16:                                                            { type: String,  trim: true },
M5008A_Actual17:                                                            { type: String,  trim: true },
M5008A_Actual18:                                                            { type: String,  trim: true },
M5008A_Actual19:                                                            { type: String,  trim: true },
M5008A_Actual20:                                                            { type: String,  trim: true },
M5008A_Actual21:                                                            { type: String,  trim: true },
M5008A_Actual22:                                                            { type: String,  trim: true },
M5008A_Actual23:                                                            { type: String,  trim: true },M5008A_Actual24:                                                            { type: String,  trim: true },
M5008A_Actual25:                                                            { type: String,  trim: true },
M5008A_Actual26:                                                            { type: String,  trim: true },
M5008A_Actual27:                                                            { type: String,  trim: true },
M5008A_Actual28:                                                            { type: String,  trim: true },
M5008A_Actual29:                                                            { type: String,  trim: true },
M5008A_Actual30:                                                            { type: String,  trim: true },
M5008A_Actual31:                                                            { type: String,  trim: true },
M5008A_Actual32:                                                            { type: String,  trim: true },

//M5017

M5017_Bogie_Bolster_No:                                                 { type: String,  trim: true },
M5017_Date:                                                             { type: String,  trim: true },
M5017_Nature_Qc_Inspection:                                             { type: String,  trim: true },
M5017_Sub_Assembly:                                                     { type: String,  trim: true },
M5017_Component_No:                                                    { type: String,  trim: true },
M5017_Stage:                                                            { type: String,  trim: true },
M5017_Status:                                                           { type: String,  trim: true },
M5017_Observation_asUnder:                                              { type: String,  trim: true },
M5017_Observed_value1:                                                 { type: String,  trim: true },
M5017_Observed_value2:                                                 { type: String,  trim: true },
M5017_Observed_value3:                                                 { type: String,  trim: true },
M5017_Observed_value4:                                                 { type: String,  trim: true },
M5017_Observed_value5:                                                 { type: String,  trim: true },
M5017_Observed_value6:                                                 { type: String,  trim: true },
M5017_Observed_value7:                                                 { type: String,  trim: true },
M5017_Remark1:                                                         { type: String,  trim: true },
M5017_Remark2:                                                         { type: String,  trim: true },
M5017_Remark3:                                                         { type: String,  trim: true },
M5017_Remark4:                                                         { type: String,  trim: true },
M5017_Remark5:                                                         { type: String,  trim: true },
M5017_Remark6:                                                         { type: String,  trim: true },
M5017_Remark7:                                                         { type: String,  trim: true },

//M5023
M5023_Bogie_Bolster_No:                                                 { type: String,  trim: true },
M5023_Date:                                                             { type: String,  trim: true },
M5023_Nature_Qc_Inspection:                                             { type: String,  trim: true },
M5023_Sub_Assembly:                                                     { type: String,  trim: true },
M5023_Component_No:                                                    { type: String,  trim: true },
M5023_Stage:                                                            { type: String,  trim: true },
M5023_Status:                                                           { type: String,  trim: true },
M5023_Observation_asUnder:                                              { type: String,  trim: true },
M5023_Observed_value1:                                                 { type: String,  trim: true },
M5023_Observed_value2:                                                 { type: String,  trim: true },
M5023_Observed_value3:                                                 { type: String,  trim: true },
M5023_Observed_value4:                                                 { type: String,  trim: true },
M5023_Observed_value5:                                                 { type: String,  trim: true },
M5023_Observed_value6:                                                 { type: String,  trim: true },
M5023_Observed_value7:                                                 { type: String,  trim: true },
M5023_Observed_value8:                                                 { type: String,  trim: true },
M5023_Observed_value9:                                                 { type: String,  trim: true },
M5023_Observed_value10:                                                 { type: String,  trim: true },
M5023_Observed_value11:                                                 { type: String,  trim: true },
M5023_Observed_value12:                                                 { type: String,  trim: true },
M5023_Remark1:                                                         { type: String,  trim: true },
M5023_Remark2:                                                         { type: String,  trim: true },
M5023_Remark3:                                                         { type: String,  trim: true },
M5023_Remark4:                                                         { type: String,  trim: true },
M5023_Remark5:                                                         { type: String,  trim: true },
M5023_Remark6:                                                         { type: String,  trim: true },
M5023_Remark7:                                                         { type: String,  trim: true },
M5023_Remark8:                                                         { type: String,  trim: true },
M5023_Remark9:                                                         { type: String,  trim: true },
M5023_Remark10:                                                         { type: String,  trim: true },
M5023_Remark11:                                                         { type: String,  trim: true },
M5023_Remark12:                                                         { type: String,  trim: true },

// wheel modal
wheel_Date: {type:String,trim:true},
input1:     {type:String,trim:true},
input2:     {type:String,trim:true},
input3:     {type:String,trim:true},
input4:     {type:String,trim:true},
input5:     {type:String,trim:true},
input6:     {type:String,trim:true},
input7:     {type:String,trim:true},
input8:     {type:String,trim:true},
input9:     {type:String,trim:true},
input10:     {type:String,trim:true},
input11:     {type:String,trim:true},
input12:     {type:String,trim:true},
input13:     {type:String,trim:true},
wheel_checked1: {type:String,trim:true},
wheel_checked2: {type:String,trim:true},
note:       {type:String,trim:true}









});

// Model
const AC2TModel = mongoose.model("ac2t", ac2tSchema);

export default AC2TModel;
